In [2]:
# Create a random tensor with shape (7, 7).
import torch
tensor = torch.rand(7, 7)
tensor

tensor([[0.9582, 0.1223, 0.8808, 0.9532, 0.7089, 0.0852, 0.0117],
        [0.5627, 0.6084, 0.4738, 0.1623, 0.5076, 0.3154, 0.8969],
        [0.1395, 0.7232, 0.0564, 0.3326, 0.0712, 0.5234, 0.2879],
        [0.5055, 0.1714, 0.7598, 0.0550, 0.7836, 0.7932, 0.6552],
        [0.0684, 0.6775, 0.0989, 0.3303, 0.6812, 0.4985, 0.9125],
        [0.9501, 0.8831, 0.8002, 0.8325, 0.2819, 0.3297, 0.0182],
        [0.2321, 0.9116, 0.3586, 0.9351, 0.3088, 0.4344, 0.5606]])

In [4]:
# Perform a matrix multiplication on the tensor from 2 
# with another random tensor with shape (1, 7) 
#(hint: you may have to transpose the second tensor).
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[1.2841],
        [1.4883],
        [1.7183],
        [1.3397],
        [1.1608],
        [1.1422],
        [1.6439]])


In [7]:
#Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [8]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() 
# but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [11]:
# Create two random tensors of shape (2, 3) and send them both to the GPU 
# (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors 
# (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)
tensor_A = torch.rand(2, 3, device="cuda")
tensor_B = torch.rand(2, 3, device="cuda")

AssertionError: Torch not compiled with CUDA enabled