In [4]:
# Create a random tensor with shape (7, 7).
import torch
tensor = torch.rand(7, 7)
tensor

tensor([[0.4116, 0.5669, 0.4611, 0.4767, 0.6993, 0.9830, 0.1307],
        [0.0027, 0.2342, 0.4703, 0.0865, 0.0036, 0.5895, 0.7870],
        [0.3717, 0.8555, 0.7964, 0.4646, 0.8175, 0.8297, 0.8926],
        [0.0724, 0.4737, 0.1734, 0.4421, 0.6611, 0.6302, 0.3769],
        [0.2150, 0.4269, 0.3739, 0.5803, 0.9296, 0.4637, 0.9570],
        [0.0279, 0.5096, 0.1516, 0.1953, 0.8233, 0.7534, 0.4731],
        [0.4433, 0.3361, 0.7818, 0.3536, 0.4530, 0.1425, 0.5521]])

In [5]:
# Perform a matrix multiplication on the tensor from 2 
# with another random tensor with shape (1, 7) 
#(hint: you may have to transpose the second tensor).
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[3.0309],
        [2.1748],
        [1.5700],
        [1.4983],
        [2.0202],
        [2.4908],
        [2.4459]])


In [6]:
#Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [7]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() 
# but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [8]:
# Create two random tensors of shape (2, 3) and send them both to the GPU 
# (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors 
# (this doesn't have to be the GPU random seed).
torch.cuda.manual_seed(1234)
tensor_A = torch.rand(2, 3, device="cuda")
tensor_B = torch.rand(2, 3, device="cuda")
print(tensor_A, "\n",tensor_B)

AssertionError: Torch not compiled with CUDA enabled

In [14]:
# Perform a matrix multiplication on the tensors you created in 6 
# (again, you may have to adjust the shapes of one of the tensors).
newTensor = torch.matmul(tensor_A, tensor_B.T)
print(newTensor)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [15]:
# Find the maximum and minimum values of the output of 7.
print(newTensor.max())
print(newTensor.min())

tensor(3.0481)
tensor(1.7067)


In [16]:
#Find the maximum and minimum index values of the output of 7.
print(newTensor.argmax())
print(newTensor.argmin())

tensor(3)
tensor(4)


In [17]:
# Make a random tensor with shape (1, 1, 1, 10) and 
# then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and 
# print out the first tensor and it's shape as well as the second tensor and it's shape.

In [18]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
newTensor = tensor.squeeze()
print(tensor)
print(tensor.shape)
print("--------")
print(newTensor)
print(newTensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
--------
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
