In [30]:
# Create a random tensor with shape (7, 7).
import torch
tensor = torch.rand(7, 7)
tensor

tensor([[0.7837, 0.5631, 0.7749, 0.8208, 0.2793, 0.6817, 0.2837],
        [0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757, 0.7842, 0.1525, 0.6662],
        [0.3343, 0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265],
        [0.9561, 0.0770, 0.4108, 0.0014, 0.5414, 0.6419, 0.2976],
        [0.7077, 0.4189, 0.0655, 0.8839, 0.8083, 0.7528, 0.8988],
        [0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541, 0.4333]])

In [31]:
# Perform a matrix multiplication on the tensor from 2 
# with another random tensor with shape (1, 7) 
#(hint: you may have to transpose the second tensor).
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[1.2027],
        [0.6421],
        [0.9253],
        [1.4599],
        [1.0091],
        [1.6087],
        [1.4622]])


In [32]:
#Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [33]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() 
# but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [34]:
# Create two random tensors of shape (2, 3) and send them both to the GPU 
# (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors 
# (this doesn't have to be the GPU random seed).
torch.cuda.manual_seed(1234)
tensor_A = torch.rand(2, 3, device="cuda")
tensor_B = torch.rand(2, 3, device="cuda")
print(tensor_A, "\n",tensor_B)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') 
 tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


In [35]:
# Perform a matrix multiplication on the tensors you created in 6 
# (again, you may have to adjust the shapes of one of the tensors).
newTensor = torch.matmul(tensor_A, tensor_B.T)
print(newTensor)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


In [36]:
# Find the maximum and minimum values of the output of 7.
print(newTensor.max())
print(newTensor.min())

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


In [37]:
#Find the maximum and minimum index values of the output of 7.
print(newTensor.argmax())
print(newTensor.argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')


In [38]:
# Make a random tensor with shape (1, 1, 1, 10) and 
# then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and 
# print out the first tensor and it's shape as well as the second tensor and it's shape.

In [41]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
newTensor = tensor.squeeze()
print(tensor)
print(tensor.shape)
print("--------")
print(newTensor)
print(newTensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
--------
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
