In [11]:
import torch
torch.__version__

'2.4.0'

Tensors are the fundamental building block of machine learning.
Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

Creating tensors
The first thing we're going to create is a scalar.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [17]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print("Amount of dimensions: ", scalar.ndim)

tensor(7)
Amount of dimensions:  0


In [18]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Okay, now let's see a vector.

A vector is a single dimension tensor but can contain many numbers.

As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

The important trend here is that a vector is flexible in what it can represent (the same with tensors).

In [19]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print("Amount of dimensions: ", vector.ndim)

tensor([7, 7])
Amount of dimensions:  1


In [20]:
# Check shape of vector
vector.shape

torch.Size([2])

In [21]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
# Check number of dimensions
MATRIX.ndim

2

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype


(tensor([[0.0751, 0.9326, 0.3304, 0.2004],
         [0.0608, 0.3213, 0.4176, 0.5107],
         [0.9020, 0.8112, 0.0551, 0.2524]]),
 torch.float32)

In [28]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the size parameter comes into play.

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [31]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [37]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [38]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2870, 0.9527, 0.7873, 0.6513],
        [0.9196, 0.8655, 0.2943, 0.1046],
        [0.1346, 0.2187, 0.6048, 0.1341]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [39]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [40]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [46]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [47]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [48]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [49]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [50]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [2]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [3]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [4]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [5]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [7]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
print(len(tensor))
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

3
CPU times: user 1.45 ms, sys: 1.01 ms, total: 2.45 ms
Wall time: 1.97 ms


tensor(14)

In [8]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 237 μs, sys: 68 μs, total: 305 μs
Wall time: 235 μs


tensor(14)

In [9]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [59]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [60]:
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [61]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [66]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [67]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [69]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [70]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [71]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [72]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [25]:
# torch.reshape(input, shape) Method
a = torch.arange(4.)
print(torch.reshape(a, (2, 2)))

b = torch.tensor([[0, 1], [2, 3]])
print(torch.reshape(b, (-1,)))

b = torch.tensor([[0, 1], [2, 3], [4, 5], [6, 7]])
print(torch.reshape(b, (2, -1)))  # Reshape into 2 rows, PyTorch calculates the number of columns

tensor([[0., 1.],
        [2., 3.]])
tensor([0, 1, 2, 3])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [32]:
x = torch.randn(4, 4)
print(x.size())
print(x)

torch.Size([4, 4])
tensor([[-1.0497,  1.0982,  1.1001,  1.8579],
        [-0.6238,  0.2020,  0.3711,  1.7753],
        [ 0.3109, -0.0320,  1.2067, -1.3208],
        [-0.1934,  0.2224, -0.5515, -0.0079]])


In [33]:
y = x.view(16)
print(y.size())
print(y)

torch.Size([16])
tensor([-1.0497,  1.0982,  1.1001,  1.8579, -0.6238,  0.2020,  0.3711,  1.7753,
         0.3109, -0.0320,  1.2067, -1.3208, -0.1934,  0.2224, -0.5515, -0.0079])


In [34]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())
print(z)

torch.Size([2, 8])
tensor([[-1.0497,  1.0982,  1.1001,  1.8579, -0.6238,  0.2020,  0.3711,  1.7753],
        [ 0.3109, -0.0320,  1.2067, -1.3208, -0.1934,  0.2224, -0.5515, -0.0079]])


In [36]:
a = torch.randn(1, 2, 3, 4)
print(a.size())
print(a)

torch.Size([1, 2, 3, 4])
tensor([[[[-1.4984,  0.3235,  0.8873,  0.2340],
          [-0.5957,  1.2520, -1.1947,  0.5507],
          [-0.2903,  0.3560,  0.0850, -0.3601]],

         [[ 1.1781, -0.0547, -0.0514, -0.0684],
          [ 0.2389, -1.3423,  0.9703,  0.2022],
          [-0.9268,  0.6879,  0.7707,  0.8273]]]])


In [44]:
b = a.transpose(1, 2)  # Swaps 2nd and 3rd dimension
print(b.size())
print(b)

torch.Size([1, 3, 2, 4])
tensor([[[[-1.4984,  0.3235,  0.8873,  0.2340],
          [ 1.1781, -0.0547, -0.0514, -0.0684]],

         [[-0.5957,  1.2520, -1.1947,  0.5507],
          [ 0.2389, -1.3423,  0.9703,  0.2022]],

         [[-0.2903,  0.3560,  0.0850, -0.3601],
          [-0.9268,  0.6879,  0.7707,  0.8273]]]])


In [49]:
c = a.view(1, 3, 2, 4)  # Does not change tensor layout in memory
print(c.size())

print(torch.equal(b, c))

torch.Size([1, 3, 2, 4])
False


In [50]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [62]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [63]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [68]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [69]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
